apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app  # Matches the label in the deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer